### ISSUE TITLE
/proc/$pid/maps parsing too inflexible

### ISSUE THREAD

**Issue by voidc** [haxkor/forkever#1]
Hi, when I tried to run forkever I got the error message:
```
Traceback (most recent call last):
  File "./forkever.py", line 52, in <module>
    main()
  File "./forkever.py", line 34, in main
    handler = InputHandler(launch_args, startupfile=parsed_args.init, inputsock=parsed_args.sock)
  File "/home/pwn/forkever/InputHandler.py", line 20, in __init__
    self.manager = ProcessManager(launch_args, self.inputPoll)
  File "/home/pwn/forkever/ProcessManager.py", line 25, in __init__
    self.debugger = self.startDebugger(args)
  File "/home/pwn/forkever/ProcessManager.py", line 48, in startDebugger
    newProcess = ProcessWrapper(args=args, debugger=debugger, redirect=True)  # first process
  File "/home/pwn/forkever/ProcessWrapper.py", line 94, in __init__
    self.programinfo = ProgramInfo(args[1], self.getPid(), self)
  File "/home/pwn/forkever/utilsFolder/ProgramInfo.py", line 22, in __init__
    self.elf = self._getElf(path_to_hack) if path_to_hack else None
  File "/home/pwn/forkever/utilsFolder/ProgramInfo.py", line 34, in _getElf
    maps = getMappings(self.pid, lib)
  File "/home/pwn/forkever/utilsFolder/MapsReader.py", line 65, in getMappings
    result= list(makeMapObj(line) for line in filter(func, maps.readlines()))
  File "/home/pwn/forkever/utilsFolder/MapsReader.py", line 65, in <genexpr>
    result= list(makeMapObj(line) for line in filter(func, maps.readlines()))
  File "/home/pwn/forkever/utilsFolder/MapsReader.py", line 52, in makeMapObj
    int(match.group(1), 16),
AttributeError: 'NoneType' object has no attribute 'group'
```
This is caused by [`PROC_MAP_REGEX.match(line)`](https://github.com/haxkor/forkever/blob/3f7e8a70b49eeacf9b07f5928d197bc88741d0ce/utilsFolder/MapsReader.py#L49) returning None.
Further investigation showed that it tries to parse:
```
564294e87000-564294e89000 r-xp 00000000 103:05 2949766                   /home/pwn/vuln
```
Here the regex does not match as it expects the device part to be exactly 5 characters long.

**Comment by haxkor** [comment]
Thanks for bringing it up and telling me what the exact issue was! I hope this did not stop you from using it:)
