### ISSUE TITLE
Crash whenever a non-ascii character is typed

### ISSUE THREAD

**Issue by 0liCom** [haxkor/forkever#2]
For example the character "ä" is encoded as 0xa7 on my keymap (which is of course not a valid ascii byte)
Instead of just ignoring this character, the program produces this crash and then softlocks:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/readline.py", line 398, in readline
    keymap.handle_input()
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/keymap.py", line 24, in handle_input
    self.send(key.get())
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/keymap.py", line 54, in send
    self._on_nomatch(self.trace)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/readline.py", line 142, in self_insert
    insert_text(k.code)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/readline.py", line 243, in insert_text
    redisplay()
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/readline.py", line 126, in redisplay
    buffer_handle.update(s)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 187, in update
    update(self.h, s)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 536, in update
    render_from(i, clear_after = True)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 454, in render_from
    render_cell(c, clear_after = clear_after)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 357, in render_cell
    put(c)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 164, in put
    fd.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pwn/forkever/utilsFolder/InputReader.py", line 32, in run
    for line in iter(stdin.readline, ""):
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/readline.py", line 488, in readline
    return readline(size)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/readline.py", line 413, in readline
    buffer_handle.update(line)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 187, in update
    update(self.h, s)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 536, in update
    render_from(i, clear_after = True)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 454, in render_from
    render_cell(c, clear_after = clear_after)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 357, in render_cell
    put(c)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/term/term.py", line 164, in put
    fd.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 0: ordinal not in range(128)
Unhandled exception in thread started by <bound method Thread._bootstrap of <InputReader(Thread-1, started daemon 140414411601664)>>
```

**Comment by haxkor** [comment]
Hi, i could not replicate the issue. 
Writing "ä" works fine.
Can you replicate this in a small python script (without forkever)?
